config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'
  resources :pages, only: :show
  resources :posts, only: [:new, :show, :create, :destroy]
  resources :likes, only: :create
  namespace :api, format: 'json' do
    resources :books, only: [:index, :create, :destroy,:update]
  end
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  resources :booklists, only: [:index]
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_one :post, dependent: :destroy
  accepts_nested_attributes_for :post

  validates :title, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }
  validate :cannot_like_own_post

  private

  def cannot_like_own_post
    errors.add(:base, "自分の投稿にいいねをつけることはできません.") if user_id == post.user_id
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :book
  has_many :likes, dependent: :destroy

  validates :content, presence: true
  validates :content, length: { maximum: 144 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follow, class_name: "User"
  belongs_to :followed, class_name: "User"

  validate :cannot_follow_myself

  private

  def cannot_follow_myself
    errors.add(:followed, "自分をフォローすることは出来ません！") if follow_id == followed_id
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :books, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :relationships, class_name: "Relationship", foreign_key: "follow_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follow

  validates :name, presence: true

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com', name: 'ゲストユーザー') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/api/books_controller.rb
class Api::BooksController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @books = current_user.books.all
  end

  def create
    @book = current_user.books.new(book_params)
    if @book.save
      render :show, status: :created
    else
      render json: @book.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
  end

  def update
    @book = Book.find_by(id: params[:id])
    @book.update(book_params)
  end

  private
    def book_params
      params.require(:book).permit(:title, :page_count, :reading_now, :finished, :reading_at)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/booklists_controller.rb
class BooklistsController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @like = current_user.likes.new(post: @post)
    if @like.invalid?
      flash[:alert] = @like.errors.full_messages.to_sentence
    else
      @like.save
    end
    redirect_to root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @posts = Post.all.page(params[:page]).per(5)
    post_ids = Like.group(:post_id).order('count(post_id) desc').pluck(:post_id)
    @post_like_ranks = Post.where(id: post_ids).page(params[:page]).per(5)
  end

  def show
    @user = User.find(params[:id])
    @books =  @user.books.where(finished: true)
    @current_month_reads = @books.where(reading_at: Time.current.all_month)
    @current_year_reads = @books.where(reading_at: Time.current.all_year)
    @posts = @user.posts.page(params[:page]).per(10)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :destroy]
  def new
    @book = current_user.books.find(params[:book_id])
    @post = current_user.posts.build(book: @book)
  end

  def create
    @book = current_user.books.find(params[:post][:book_id])
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:notice] = "投稿が作成されました"
      redirect_to page_path(current_user)
    else
      flash[:alert] = "投稿の作成に失敗しました"
      render :new, locals: { book_id: params[:post][:book_id] }
    end
  end

  def destroy
  end

  private

  def post_params
    params.require(:post).permit(:content, :book_id)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    user = User.find(params[:user_id])
    if current_user.following?(user)
      flash[:error] = "もうこのユーザーはフォローされています."
    elsif user == current_user
      flash[:error] = "自分をフォローすることはできません."
    else
      current_user.follow(user)
      flash[:success] = "#{user.name}をフォローしました！."
    end
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/api/books_helper.rb
module Api::BooksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/booklist_helper.rb
module BooklistHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reabit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'header' %>
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/vuetify@2.x/dist/vuetify.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/@mdi/font@5.x/css/materialdesignicons.min.css" rel="stylesheet">
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<div class="d-flex flex-column col-12 justify-content-center">
  <div class="col-8 d-flex flex-column mx-auto">
    <div class="content">
      <div class="bg-white d-flex flex-column">
        <% if !user_signed_in? %>
          <div class="d-flex flex-column justify-content-center align-items-center">
            <h4>Reabitは読書習慣をサポートするアプリです。</h4>
            <h5>どんな機能があるか試してみましょう</h5>
            <%= link_to "簡単ログイン", users_guest_sign_in_path, method: :post, class:'btn btn-outline-success col-4' %>
          </div>
        <% else %>
          <h4>Reabitは読書習慣をサポートするアプリです。</h4>
          <p>まずは投稿から読んで見たい本を探してみましょう</p>
          <p>1、本を見つけたらBookListで自分が気になった本を登録しましょう。</p>
          <p>2、BookListでは「今読んでいる本」「読み終わった本」「後で読む本」を確認することができます。</p>
          <p>3、本を読み終わったらどんな人におすすめか本について学んだこと等を紹介してみましょう</p>
        <% end %>
      </div>
    </div>
    <div class="d-flex flex-wrap justify-content-center mt-5">
      <div class="col-12 col-md-6">
        <%= render partial: 'shared/posts', locals: { postsTitle: "人気投稿",posts: @post_like_ranks, param_name: "post_like_ranks" } %>
      </div>
      <div class="col-12 col-md-6">
        <%= render partial: 'shared/posts', locals: { postsTitle: "新規投稿",posts: @posts, param_name: "posts" } %>
      </div>
      <%= paginate @posts %>
    </div>
  </div>
</div>

app/views/pages/show.html.erb
<div class="d-flex flex-column ms-5">
  <div class="d-flex col-12">
    <h1 class="col-8"><%= @user.name %></h1>
    <div class="d-flex align-items-center col-4">
      <% if current_user == @user %>
        <%= link_to "ユーザー情報を編集する",edit_user_registration_path %>
      <% else %>
        <% if current_user.following?(@user) %>
          <%= link_to "フォロー外す", user_relationships_path(@user.id), method: :delete %>
        <% else %>
          <%= link_to "フォローする", user_relationships_path(@user.id), method: :post %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="d-flex col-12">
    <p class="col-3">フォロー数: <%= @user.followings.count %></p>
    <p class="col-3">フォロワー数: <%= @user.followers.count %></p>
    <p class="col-3">今月で読んだ冊数: <%=  @current_month_reads.count %></p>
    <p class="col-3">今年読んだ本数: <%= @current_year_reads.count %></p>
  </div>
</div>
<div class="d-flex flex-wrap justify-content-center mt-2">
  <div class="col-12 col-md-6">
    <div class="card m-3">
      <div class="card-body">
        <h2 class="card-title">読んだ本一覧</h2>
        <% @books.each do |book| %>
          <div class="card mt-2">
            <div class="card-body d-flex flex-column justify-content-around">
              <div class="d-flex align-items-center">
                <p class="fs-4"><%= book.title %></p>
                <% if book.reading_at %>
                  <p class="ms-2">読み終わった日: <%= book.reading_at.strftime('%Y-%m-%d')%></p>
                <% end %>
              </div>
              <div class="d-flex justify-content-end">
                <%= link_to "投稿する", new_post_path(book_id: book.id) %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-12 col-md-6">
    <%= render partial: 'shared/posts', locals: { postsTitle: "直近の投稿",posts: @posts } %>
    <%= paginate @posts %>
  </div>
</div>

app/views/shared/_header.html.erb
<header class="container-fluid sticky-top bg-white border border-light border-5">
      <% if flash[:notice] %>
        <div class="alert alert-info">
          <%= flash[:notice] %>
        </div>
      <% end %>
      <% if flash[:alert] %>
        <div class="alert alert-danger">
          <%= flash[:alert] %>
        </div>
      <% end %>
      <div class="header d-flex container-fluid justify-content-between flex-wrap col-12">
        <div class="d-flex align-items-center col-6">
          <%= image_tag "Reabit-logo.png", class: "img", id:"logo"%>
          <h4>Reabit</h4>
        </div>
        <div class="d-flex justify-content-end">
          <nav class="global-nav navbar navbar-expand-xl d-flex container-fluid align-items-center">
            <button class="navbar-toggle d-block d-xl-none">
              <i class="fas fa-bars" onclick="clickBtn1()" id="toggle-btn"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="d-flex", style="list-style: none;">
                <li class="nav-item mx-1">
                    <%= link_to "Home", root_path, class:'btn btn-outline-primary link' %>
                </li>
                <% if !user_signed_in? %>
                  <li class="nav-item mx-1">
                    <%= link_to "ログイン",new_user_session_path , class:'btn btn-outline-primary' %>
                  </li>
                <% end %>
                <% if user_signed_in? %>
                  <li class="nav-item mx-1">
                    <%= link_to "本棚", booklists_path , class:'btn btn-outline-primary' %>
                  </li>
                  <li class="nav-item mx-1">
                    <%= link_to "ユーザーページ", page_path(current_user), class:'btn btn-outline-primary' %>
                  </li>
                  <li class="nav-item mx-1">
                    <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:'btn btn-outline-danger' %>
                  </li>
                <% end %>
              </ul>
            </div>
            <div class="col-12 d-xl-none" id="nav_for_Hamburger">
              <ul class="d-flex flex-wrap", style="list-style: none;">
                <li class="nav-item mx-1 col-12">
                  <%= link_to "Home", root_path, class:'link' %>
                </li>
                <% if !user_signed_in? %>
                  <li class="nav-item mx-1 col-12">
                    <%= link_to "ログイン",new_user_registration_path , class:'link' %>
                  </li>
                <% end %>
                <% if user_signed_in? %>
                  <li class="nav-item mx-1 col-12">
                    <%= link_to "本棚", booklists_path , class:'link' %>
                  </li>
                  <li class="nav-item mx-1 col-12">
                    <%= link_to "ユーザーページ", page_path(current_user), class:'btn btn-outline-primary' %>
                  </li>
                  <li class="nav-item mx-1 col-12">
                    <%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: { confirm: '本当にログアウトしますか？' }, remote: true, class:'link' %>
                  </li>
                <% end %>
              </ul>
            </nav>
          </div>
        </div>
      </header>

app/views/shared/_posts.html.erb
<div class="card m-3">
  <div class="card-body">
    <h2 class="card-title"><%= postsTitle %></h2>
    <% posts.each do |post| %>
      <div id="post_<%= post.id %>" class="card mb-3">
        <div class="card-header bg-white d-flex justify-content-between">
          <p class="card-title"><%= post.book.title %></p>
          <%= link_to post.user.name, page_path(post.user.id) %>
        </div>
        <div class="card-body border-top">
          <div class="ms-2">
            <p class="card-text text-wrap"><%= post.content %></p>
          </div>
          <div class="d-flex justify-content-end">
            <% if user_signed_in? && current_user.id != post.user.id%>
              <% if current_user.likes.exists?(post: post)%>
                <p class="pt-2">いいね済みです。</p>
              <% else %>
                <%= button_to 'いいね', likes_path(post_id: post.id), method: :post, class: "btn btn-outline-primary" %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>